name: Python CI Pipeline

on:
  push:
    branches:
      - skillo_dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

      - name: pytest and pytest-cov
        run: |
          python -m pip install --upgrade pip
          pip install numpy scipy pytest pytest-cov

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
    
      - name: Run tests with coverage
        run: |
          pytest --cov=. --cov-report=html 

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov

  sphinx-docs:
    runs-on: ubuntu-latest
    needs: build  # This ensures the documentation job runs after the test job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd):$PYTHONPATH" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install sphinx  # Make sure Sphinx is installed

      - name: Build Sphinx documentation
        run: |
          cd docs  # Navigate to the docs directory
          sphinx-build -b html . _build/html  # Build the docs to _build/html

      - name: Upload documentation as artifact
        uses: actions/upload-artifact@v3
        with:
          name: sphinx-docs
          path: docs/_build/html  # Upload the generated HTML docs
