name: Sphinx Documentation

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  sphinx-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd):$PYTHONPATH" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          pip install sphinx 

      - name: Build Sphinx documentation
        run: |
          cd docs  # Navigate to the docs directory
          sphinx-build -b html source _build/html  # Build the docs

      - name: Upload documentation as artifact
        uses: actions/upload-artifact@v3
        with:
          name: sphinx-docs 
          path: docs/_build/html 

